//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StateLight.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public int LedBrightness {
            get {
                return ((int)(this["LedBrightness"]));
            }
            set {
                this["LedBrightness"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\STATE_LED")]
        public string UsbIdSearch {
            get {
                return ((string)(this["UsbIdSearch"]));
            }
            set {
                this["UsbIdSearch"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool WatchdogActive {
            get {
                return ((bool)(this["WatchdogActive"]));
            }
            set {
                this["WatchdogActive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("22")]
        public int MenuHeight {
            get {
                return ((int)(this["MenuHeight"]));
            }
            set {
                this["MenuHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("150")]
        public int MenuWidth {
            get {
                return ((int)(this["MenuWidth"]));
            }
            set {
                this["MenuWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"
					Verfügbar:#00FF00
					Beschäftig:#FFFF00
					Am Telefon:#FF0000
					Rot blinkend:#FF0000b
					Weiss:#FFFFFF
					Violet:#FF00FF
					Türkis:#00FFFF
					Blau:#0000FF
					Orange:#FF7F00
					Hellblau:#3F3FFF
					Farbtest:#FF0000-#00FF00-#0000FF-#FFFF00-#FFFFFFb-#FF00FF
					Rot/Grün:#FF0000-#FF0000-#00FF00-#00FF00-#FF0000-#FF0000
					Ausgeschaltet:#000000
				")]
        public string States {
            get {
                return ((string)(this["States"]));
            }
            set {
                this["States"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\r\n\t\t\t\t\tFree:#00FF00\r\n\t\t\t\t\tFreeIdle:#00FF00\r\n\t\t\t\t\tBusy:#FFFF00\r\n\t\t\t\t\tBusyIdle:#FFF" +
            "F00\r\n\t\t\t\t\tDoNotDisturb:#FF0000\r\n\t\t\t\t\tAway:#0000FF\r\n\t\t\t\t\tTemporarilyAway:#0000FF\r" +
            "\n\t\t\t\t\tOffline:#FFFFFF\r\n\t\t\t\t\tsigned-out:#555555-#555555-#00FF00-#FF0000-#555555-#" +
            "555555\r\n\t\t\t\t")]
        public string StateMapping {
            get {
                return ((string)(this["StateMapping"]));
            }
            set {
                this["StateMapping"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AutostartPlugin {
            get {
                return ((bool)(this["AutostartPlugin"]));
            }
            set {
                this["AutostartPlugin"] = value;
            }
        }
    }
}
